lib/dotes_web/router.ex
defmodule DotesWeb.Router do
  use Dotes.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
  end

  scope "/", DotesWeb do
    pipe_through :browser # Use the default browser stack

    get "/", RollController, :index
    
    get "/matches/delete_all", MatchController, :delete_all
    get "/matches/get_recent", MatchController, :get_recent
    resources "/matches", MatchController

    resources "/users", UserController
    get "/users/:id/get", UserController, :get
    get "/users/:id/get_all", UserController, :get_all
    
    post "/rolls/go", RollController, :go
    resources "/rolls", RollController
  end

  # Other scopes may use custom stacks.
  scope "/api", DotesWeb do
    pipe_through :api
    resources "/rolls", RollApiController, only: [:index]
  end
end

web/router.ex
defmodule Dotes.Router do
  use Dotes.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Dotes do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    
    get "/matches/delete_all", MatchController, :delete_all
    get "/matches/get_recent", MatchController, :get_recent
    resources "/matches", MatchController

    resources "/users", UserController
    get "/users/:id/get", UserController, :get
    get "/users/:id/get_all", UserController, :get_all
    
    post "/rolls/go", RollController, :go
    resources "/rolls", RollController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Dotes do
  #   pipe_through :api
  # end
end

lib/dotes_web/views/player_view.ex
defmodule DotesWeb.PlayerView do
  use Dotes.Web, :view

  def item_img(id, opts \\ []) do
    case Dota.Item.get(id) do
      nil -> nil
      item ->
        tag :img, [{:src, "/images/items/#{item["name"]}_lg.png"} | opts]
    end
  end

  def hero_img(id, size \\ "sb.png") do
    case Dota.Hero.get(id) do
      nil -> nil
      hero ->
        tag :img, src: "/images/heroes/#{hero["name"]}_#{size}"
    end
  end
end

web/views/player_view.ex
defmodule Dotes.PlayerView do
  use Dotes.Web, :view

  def item_img(id, opts \\ []) do
    case Dota.Item.get(id) do
      nil -> nil
      item ->
        tag :img, [{:src, "/images/items/#{item["name"]}_lg.png"} | opts]
    end
  end

  def hero_img(id, size \\ "sb.png") do
    case Dota.Hero.get(id) do
      nil -> nil
      hero ->
        tag :img, src: "/images/heroes/#{hero["name"]}_#{size}"
    end
  end
end

lib/dotes_web/templates/player/player.html.eex
<tr>
  <td>
    <%= hero_img(@player.hero_id) %>
    <%= if @player.user_id do %>
      <%= link @player.user.personaname, to: user_path(@conn, :show, @player.user_id) %>
    <% else %>
      <%= Dota.Hero.localized_name(@player.hero_id) %>
    <% end %>
  </td>
  <%= content_tag :td, to_string(@player.level) %>
  <%= content_tag :td, Enum.join([@player.kills, @player.deaths, @player.assists], "/") %>
  <%= content_tag :td, to_string(@player.gold) %>
  <%= content_tag :td, to_string(@player.gold_spent) %>
  <%= content_tag :td, to_string(@player.last_hits) %>
  <%= content_tag :td, to_string(@player.denies) %>
  <%= content_tag :td, to_string(@player.gold_per_min) %>
  <%= content_tag :td, to_string(@player.xp_per_min) %>
  <%= content_tag :td, to_string(@player.hero_damage) %>
  <%= content_tag :td, to_string(@player.hero_healing) %>
  <%= content_tag :td, to_string(@player.tower_damage) %>
  <td>
    <%= item_img(@player.item_0, width: "43", height: "32") %>
    <%= item_img(@player.item_1, width: "43", height: "32") %>
    <%= item_img(@player.item_2, width: "43", height: "32") %>
    <%= item_img(@player.item_3, width: "43", height: "32") %>
    <%= item_img(@player.item_4, width: "43", height: "32") %>
    <%= item_img(@player.item_5, width: "43", height: "32") %>
  </td>
  <td>
    <%= link "match", to: match_path(@conn, :show, @match) %>
  </td>
</tr>