lib/dotes_web/router.ex
defmodule DotesWeb.Router do
  use Dotes.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
  end

  scope "/", DotesWeb do
    pipe_through :browser # Use the default browser stack

    get "/", RollController, :index
    
    get "/matches/delete_all", MatchController, :delete_all
    get "/matches/get_recent", MatchController, :get_recent
    resources "/matches", MatchController

    resources "/users", UserController
    get "/users/:id/get", UserController, :get
    get "/users/:id/get_all", UserController, :get_all
    
    post "/rolls/go", RollController, :go
    resources "/rolls", RollController
  end

  # Other scopes may use custom stacks.
  scope "/api", DotesWeb do
    pipe_through :api
    resources "/rolls", RollApiController, only: [:index]
  end
end

web/router.ex
defmodule Dotes.Router do
  use Dotes.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Dotes do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    
    get "/matches/delete_all", MatchController, :delete_all
    get "/matches/get_recent", MatchController, :get_recent
    resources "/matches", MatchController

    resources "/users", UserController
    get "/users/:id/get", UserController, :get
    get "/users/:id/get_all", UserController, :get_all
    
    post "/rolls/go", RollController, :go
    resources "/rolls", RollController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Dotes do
  #   pipe_through :api
  # end
end

lib/dotes_web/views/layout_view.ex
defmodule DotesWeb.LayoutView do
  use Dotes.Web, :view
end

lib/dotes_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phoenix!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li><%= link "Users", to: user_path(@conn, :index) %></li>
          <li><%= link "Rolls", to: roll_path(@conn, :index) %></li>
        </ul>
        <h1>Rolls</h1>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>